import type { ProcurementRunData, VendorOrder } from "@models/procurement";
import { ProcurementService } from "@services/procurement-service";

const RAW_DATA = {
  stats: {
    purchaseOrderCount: 12,
    supplierCount: 6,
    proposedSpend: 34800,
    stockOutsAtRisk: 18,
  },
  vendors: [
    {
      id: "medcore-dist",
      vendorName: "MedCore Distribution",
      supplierEmail: "s.mills@medcore-distribution.com",
      value: 8640,
      skuCount: 6,
      earliestStockout: "Mar 19",
      poSummary: {
        poNumber: "PO-1099",
        value: 8640,
        leadTimeDays: 3,
        leadTimeEta: "Mar 22",
        confidencePercent: 92,
        confidenceLabel: "High",
        skuCount: 6,
        skuNote: "2 at risk",
      },
      demandSignal: {
        summary:
          "Seasonal respiratory illness peak in progress. RX data shows a 38% week-over-week surge in antibiotic dispensing. Amoxicillin 500mg is already out of stock and Azithromycin 250mg runs out in 2 days. Immediate top-up is critical to avoid patient-level supply disruption.",
      },
      riskFactors: [
        {
          id: "rf-1",
          label: "Amoxicillin 500mg — out of stock as of Mar 17",
          severity: "critical",
        },
        {
          id: "rf-2",
          label: "Azithromycin 250mg — stockout projected Mar 21",
          severity: "critical",
        },
        {
          id: "rf-3",
          label: "API shortage notice from manufacturer (FDA DSN-20260318-AX)",
          severity: "warning",
        },
        {
          id: "rf-4",
          label: "Contract price lock expires Apr 1 — order now to protect rate",
          severity: "info",
        },
      ],
      lineItems: [
        {
          id: "li-1",
          skuCode: "AMOX500",
          name: "Amoxicillin 500mg Capsules",
          status: "out-of-stock",
          currentInventory: 0,
          runOutDate: "Mar 17",
          unitPrice: 21.0,
          recommendedQuantity: 240,
          orderValue: 5040,
        },
        {
          id: "li-2",
          skuCode: "AZIT250",
          name: "Azithromycin 250mg Tablets",
          status: "urgent",
          currentInventory: 12,
          runOutDate: "Mar 21",
          unitPrice: 18.5,
          recommendedQuantity: 180,
          orderValue: 3330,
        },
        {
          id: "li-3",
          skuCode: "MET500",
          name: "Metformin 500mg Tablets",
          status: "low-stock",
          currentInventory: 45,
          runOutDate: "Mar 25",
          unitPrice: 8.0,
          recommendedQuantity: 300,
          orderValue: 2400,
        },
        {
          id: "li-4",
          skuCode: "LISIN10",
          name: "Lisinopril 10mg Tablets",
          status: "normal",
          currentInventory: 88,
          runOutDate: "Mar 30",
          unitPrice: 9.5,
          recommendedQuantity: 200,
          orderValue: 1900,
        },
        {
          id: "li-5",
          skuCode: "ATOR20",
          name: "Atorvastatin 20mg Tablets",
          status: "normal",
          currentInventory: 64,
          runOutDate: "Mar 28",
          unitPrice: 12.0,
          recommendedQuantity: 150,
          orderValue: 1800,
        },
        {
          id: "li-6",
          skuCode: "OMEP20",
          name: "Omeprazole 20mg Capsules",
          status: "low-stock",
          currentInventory: 30,
          runOutDate: "Mar 24",
          unitPrice: 7.5,
          recommendedQuantity: 200,
          orderValue: 1500,
        },
      ],
    },
    {
      id: "clearpath-rx",
      vendorName: "ClearPath Rx",
      supplierEmail: "david.chen@clearpathrx.com",
      value: 6480,
      skuCount: 4,
      earliestStockout: "Mar 21",
      poSummary: {
        poNumber: "PO-1042",
        value: 6480,
        leadTimeDays: 5,
        leadTimeEta: "Mar 24",
        confidencePercent: 85,
        confidenceLabel: "Medium",
        skuCount: 4,
        skuNote: "1 at risk",
      },
      demandSignal: {
        summary:
          "Cardiovascular and diabetes dispensing running 14% above baseline. Insulin Glargine stock runs out Mar 21 — a 3-day gap before the revised ETA of Mar 24. Cold-chain vehicle maintenance on Mar 23 adds delivery risk. Prioritise confirming this PO today.",
      },
      riskFactors: [
        {
          id: "rf-5",
          label: "Insulin Glargine — runs out Mar 21, ETA Mar 24 (3-day gap)",
          severity: "critical",
        },
        {
          id: "rf-6",
          label: "Cold-chain vehicle scheduled maintenance Mar 23",
          severity: "warning",
        },
        {
          id: "rf-7",
          label: "Delivery window delayed 2 days — logistics disruption",
          severity: "warning",
        },
      ],
      lineItems: [
        {
          id: "li-7",
          skuCode: "INSGLA",
          name: "Insulin Glargine 100u/mL Vial",
          status: "urgent",
          currentInventory: 8,
          runOutDate: "Mar 21",
          unitPrice: 42.0,
          recommendedQuantity: 60,
          orderValue: 2520,
        },
        {
          id: "li-8",
          skuCode: "METOP50",
          name: "Metoprolol Succinate 50mg",
          status: "normal",
          currentInventory: 52,
          runOutDate: "Mar 29",
          unitPrice: 11.0,
          recommendedQuantity: 180,
          orderValue: 1980,
        },
        {
          id: "li-9",
          skuCode: "AMLO5",
          name: "Amlodipine 5mg Tablets",
          status: "low-stock",
          currentInventory: 24,
          runOutDate: "Mar 25",
          unitPrice: 9.0,
          recommendedQuantity: 180,
          orderValue: 1620,
        },
        {
          id: "li-10",
          skuCode: "RAMIP10",
          name: "Ramipril 10mg Capsules",
          status: "normal",
          currentInventory: 40,
          runOutDate: "Mar 31",
          unitPrice: 9.0,
          recommendedQuantity: 40,
          orderValue: 360,
        },
      ],
    },
    {
      id: "summit-pharma",
      vendorName: "Summit Pharma Supplies",
      supplierEmail: "james.wu@summit-pharma.com",
      value: 4960,
      skuCount: 5,
      earliestStockout: "Mar 27",
      poSummary: {
        poNumber: "PO-1047",
        value: 4960,
        leadTimeDays: 4,
        leadTimeEta: "Mar 23",
        confidencePercent: 88,
        confidenceLabel: "High",
        skuCount: 5,
        skuNote: "Partial fill",
      },
      demandSignal: {
        summary:
          "Psychiatric medication demand stable but elevated — GP referral backlog driving a 9% uptick in Sertraline dispensing. Summit Pharma has confirmed a partial fill: 80 of 160 units available now, remainder in 10–14 days. No immediate stockout risk across other SKUs.",
      },
      riskFactors: [
        {
          id: "rf-8",
          label: "Sertraline 50mg partial fill confirmed (80 of 160 units)",
          severity: "warning",
        },
        {
          id: "rf-9",
          label: "Backorder resolution expected within 10–14 days",
          severity: "info",
        },
      ],
      lineItems: [
        {
          id: "li-11",
          skuCode: "SERT50",
          name: "Sertraline 50mg Tablets",
          status: "low-stock",
          currentInventory: 18,
          runOutDate: "Mar 27",
          unitPrice: 14.0,
          recommendedQuantity: 200,
          orderValue: 2800,
        },
        {
          id: "li-12",
          skuCode: "CITAL20",
          name: "Citalopram 20mg Tablets",
          status: "normal",
          currentInventory: 56,
          runOutDate: "Apr 1",
          unitPrice: 10.5,
          recommendedQuantity: 120,
          orderValue: 1260,
        },
        {
          id: "li-13",
          skuCode: "QUETP25",
          name: "Quetiapine 25mg Tablets",
          status: "normal",
          currentInventory: 42,
          runOutDate: "Mar 30",
          unitPrice: 11.0,
          recommendedQuantity: 80,
          orderValue: 880,
        },
        {
          id: "li-14",
          skuCode: "DIAZ5",
          name: "Diazepam 5mg Tablets",
          status: "normal",
          currentInventory: 35,
          runOutDate: "Mar 29",
          unitPrice: 6.5,
          recommendedQuantity: 100,
          orderValue: 650,
        },
        {
          id: "li-15",
          skuCode: "ZOPICL",
          name: "Zopiclone 7.5mg Tablets",
          status: "normal",
          currentInventory: 70,
          runOutDate: "Apr 3",
          unitPrice: 8.0,
          recommendedQuantity: 60,
          orderValue: 480,
        },
      ],
    },
    {
      id: "alliance-medical",
      vendorName: "Alliance Medical Wholesale",
      supplierEmail: "h.adams@alliance-medical.com",
      value: 5040,
      skuCount: 8,
      earliestStockout: "Apr 2",
      poSummary: {
        poNumber: "PO-1051",
        value: 5040,
        leadTimeDays: 2,
        leadTimeEta: "Mar 21",
        confidencePercent: 95,
        confidenceLabel: "High",
        skuCount: 8,
        skuNote: "All clear",
      },
      demandSignal: {
        summary:
          "OTC analgesic demand elevated during winter flu period. Chronic disease medications stable. Alliance Medical has notified of an Atorvastatin 20mg price increase (+20%) effective April 1 — ordering this run locks in current contract pricing for the next cycle.",
      },
      riskFactors: [
        {
          id: "rf-10",
          label: "Atorvastatin 20mg price increase +20% effective April 1",
          severity: "warning",
        },
        {
          id: "rf-11",
          label: "All 8 SKUs fully allocated — on schedule for Mar 21 delivery",
          severity: "info",
        },
      ],
      lineItems: [
        {
          id: "li-16",
          skuCode: "ATOR40",
          name: "Atorvastatin 40mg Tablets",
          status: "normal",
          currentInventory: 80,
          runOutDate: "Apr 2",
          unitPrice: 14.0,
          recommendedQuantity: 120,
          orderValue: 1680,
        },
        {
          id: "li-17",
          skuCode: "SIMVA20",
          name: "Simvastatin 20mg Tablets",
          status: "normal",
          currentInventory: 95,
          runOutDate: "Apr 4",
          unitPrice: 9.0,
          recommendedQuantity: 100,
          orderValue: 900,
        },
        {
          id: "li-18",
          skuCode: "IBU400",
          name: "Ibuprofen 400mg Tablets",
          status: "normal",
          currentInventory: 60,
          runOutDate: "Mar 31",
          unitPrice: 5.0,
          recommendedQuantity: 200,
          orderValue: 1000,
        },
        {
          id: "li-19",
          skuCode: "PARA500",
          name: "Paracetamol 500mg Tablets",
          status: "normal",
          currentInventory: 48,
          runOutDate: "Mar 29",
          unitPrice: 4.0,
          recommendedQuantity: 300,
          orderValue: 1200,
        },
        {
          id: "li-20",
          skuCode: "NAPROX",
          name: "Naproxen 500mg Tablets",
          status: "normal",
          currentInventory: 72,
          runOutDate: "Apr 3",
          unitPrice: 8.5,
          recommendedQuantity: 80,
          orderValue: 680,
        },
        {
          id: "li-21",
          skuCode: "CODEIN30",
          name: "Codeine 30mg Tablets",
          status: "normal",
          currentInventory: 55,
          runOutDate: "Mar 30",
          unitPrice: 12.0,
          recommendedQuantity: 60,
          orderValue: 720,
        },
        {
          id: "li-22",
          skuCode: "TRAMA50",
          name: "Tramadol 50mg Capsules",
          status: "normal",
          currentInventory: 90,
          runOutDate: "Apr 5",
          unitPrice: 11.0,
          recommendedQuantity: 60,
          orderValue: 660,
        },
        {
          id: "li-23",
          skuCode: "CELECOX",
          name: "Celecoxib 200mg Capsules",
          status: "normal",
          currentInventory: 65,
          runOutDate: "Apr 1",
          unitPrice: 16.0,
          recommendedQuantity: 40,
          orderValue: 640,
        },
      ],
    },
    {
      id: "pharmalink-co",
      vendorName: "PharmaLink Co.",
      supplierEmail: "mark.santos@pharmalink.com",
      value: 5480,
      skuCount: 5,
      earliestStockout: "Mar 19",
      poSummary: {
        poNumber: "PO-1002",
        value: 5480,
        leadTimeDays: 2,
        leadTimeEta: "Mar 21",
        confidencePercent: 90,
        confidenceLabel: "High",
        skuCount: 5,
        skuNote: "1 backordered",
      },
      demandSignal: {
        summary:
          "Diabetes medication volumes tracking 12% above baseline. Warfarin 5mg is currently out of stock across all PharmaLink nodes — backordered until April 2. Two therapeutic alternatives identified: same-strength Warfarin (alt mfr) and Acenocoumarol 4mg (requires prescriber sign-off).",
      },
      riskFactors: [
        {
          id: "rf-12",
          label: "Warfarin 5mg — out of stock, backordered until Apr 2",
          severity: "critical",
        },
        {
          id: "rf-13",
          label: "14-day gap between current stock depletion and restock",
          severity: "critical",
        },
        {
          id: "rf-14",
          label: "Two therapeutic alternatives confirmed and available",
          severity: "info",
        },
      ],
      lineItems: [
        {
          id: "li-24",
          skuCode: "MET1000",
          name: "Metformin 1000mg Tablets",
          status: "normal",
          currentInventory: 110,
          runOutDate: "Mar 30",
          unitPrice: 10.0,
          recommendedQuantity: 300,
          orderValue: 3000,
        },
        {
          id: "li-25",
          skuCode: "GLIMEP4",
          name: "Glimepiride 4mg Tablets",
          status: "low-stock",
          currentInventory: 22,
          runOutDate: "Mar 26",
          unitPrice: 13.0,
          recommendedQuantity: 100,
          orderValue: 1300,
        },
        {
          id: "li-26",
          skuCode: "SITAGLIP",
          name: "Sitagliptin 100mg Tablets",
          status: "normal",
          currentInventory: 58,
          runOutDate: "Apr 1",
          unitPrice: 22.0,
          recommendedQuantity: 60,
          orderValue: 1320,
        },
        {
          id: "li-27",
          skuCode: "EMPAGLIFL",
          name: "Empagliflozin 10mg Tablets",
          status: "normal",
          currentInventory: 40,
          runOutDate: "Mar 29",
          unitPrice: 28.0,
          recommendedQuantity: 40,
          orderValue: 1120,
        },
        {
          id: "li-28",
          skuCode: "WARF5",
          name: "Warfarin 5mg Tablets",
          status: "out-of-stock",
          currentInventory: 0,
          runOutDate: "Mar 19",
          unitPrice: 8.0,
          recommendedQuantity: 120,
          orderValue: 960,
        },
      ],
    },
    {
      id: "cardinal-rx",
      vendorName: "Cardinal Rx Direct",
      supplierEmail: "dispatch@cardinal-rx.com",
      value: 4200,
      skuCount: 4,
      earliestStockout: "Apr 5",
      poSummary: {
        poNumber: "PO-5444",
        value: 4200,
        leadTimeDays: 3,
        leadTimeEta: "Mar 22",
        confidencePercent: 97,
        confidenceLabel: "Very High",
        skuCount: 4,
        skuNote: "Arriving early",
      },
      demandSignal: {
        summary:
          "Respiratory medications stable across all SKUs. Cardinal Rx is offering a 6% bulk pricing discount on Salbutamol inhaler orders over 80 units this week — consider increasing the order quantity to capture savings ahead of the flu season peak.",
      },
      riskFactors: [
        {
          id: "rf-15",
          label: "Delivery arriving 4 hours early — confirm receiving bay",
          severity: "info",
        },
        {
          id: "rf-16",
          label: "Bulk discount available on Salbutamol >80 units (6% off)",
          severity: "info",
        },
      ],
      lineItems: [
        {
          id: "li-29",
          skuCode: "SALB100",
          name: "Salbutamol Inhaler 100mcg",
          status: "normal",
          currentInventory: 85,
          runOutDate: "Apr 5",
          unitPrice: 18.0,
          recommendedQuantity: 60,
          orderValue: 1080,
        },
        {
          id: "li-30",
          skuCode: "BECLO200",
          name: "Beclomethasone 200mcg Inhaler",
          status: "normal",
          currentInventory: 72,
          runOutDate: "Apr 3",
          unitPrice: 24.0,
          recommendedQuantity: 40,
          orderValue: 960,
        },
        {
          id: "li-31",
          skuCode: "TIOTROPIUM",
          name: "Tiotropium 18mcg Inhaler",
          status: "normal",
          currentInventory: 50,
          runOutDate: "Apr 1",
          unitPrice: 42.0,
          recommendedQuantity: 30,
          orderValue: 1260,
        },
        {
          id: "li-32",
          skuCode: "MONT10",
          name: "Montelukast 10mg Tablets",
          status: "normal",
          currentInventory: 65,
          runOutDate: "Apr 4",
          unitPrice: 15.0,
          recommendedQuantity: 60,
          orderValue: 900,
        },
      ],
    },
  ],
} as const;

export const DEMO_PROCUREMENT_RUN: ProcurementRunData = {
  ...RAW_DATA,
  vendors: RAW_DATA.vendors.map((vendor): VendorOrder => ({
    ...vendor,
    urgency: ProcurementService.deriveVendorUrgency(vendor.lineItems),
  })),
};
