import type { ProcurementRunData, VendorOrder } from "@models/procurement";
import { ProcurementService } from "@services/procurement-service";

const RAW_DATA = {
  stats: {
    purchaseOrderCount: 12,
    supplierCount: 6,
    proposedSpend: 24800,
    stockOutsAtRisk: 18,
  },
  vendors: [
    {
      id: "medcore-dist",
      vendorName: "MedCore Distribution",
      value: 8640,
      skuCount: 6,
      earliestStockout: "Jan 23",
      poSummary: {
        poNumber: "PO-1099",
        value: 8640,
        leadTimeDays: 3,
        leadTimeEta: "Jan 25",
        confidencePercent: 92,
        confidenceLabel: "High",
        skuCount: 6,
        skuNote: "2 at risk",
      },
      demandSignal: {
        summary:
          "Flu season RX surge expected. Historical data shows 35% increase in antibiotic dispensing. Recommend increasing quantities for critical antibiotics.",
      },
      riskFactors: [
        {
          id: "rf-1",
          label: "2 SKUs out of stock by Jan 23",
          severity: "critical",
        },
        {
          id: "rf-2",
          label: "Vendor reliability score: 78%",
          severity: "warning",
        },
        {
          id: "rf-3",
          label: "Price increase pending Feb 1",
          severity: "info",
        },
      ],
      lineItems: [
        {
          id: "li-1",
          skuCode: "AMOX500",
          name: "Amoxicillin 500mg Capsules",
          status: "out-of-stock",
          currentInventory: 0,
          runOutDate: "Jan 20",
          unitPrice: 21.0,
          recommendedQuantity: 240,
          orderValue: 5040,
        },
        {
          id: "li-2",
          skuCode: "AZIT250",
          name: "Azithromycin 250mg Tablets",
          status: "urgent",
          currentInventory: 12,
          runOutDate: "Jan 23",
          unitPrice: 18.5,
          recommendedQuantity: 180,
          orderValue: 3330,
        },
        {
          id: "li-3",
          skuCode: "MET500",
          name: "Metformin 500mg Tablets",
          status: "low-stock",
          currentInventory: 45,
          runOutDate: "Jan 26",
          unitPrice: 8.0,
          recommendedQuantity: 300,
          orderValue: 2400,
        },
        {
          id: "li-4",
          skuCode: "LISIN10",
          name: "Lisinopril 10mg Tablets",
          status: "normal",
          currentInventory: 88,
          runOutDate: "Jan 30",
          unitPrice: 9.5,
          recommendedQuantity: 200,
          orderValue: 1900,
        },
        {
          id: "li-5",
          skuCode: "ATOR20",
          name: "Atorvastatin 20mg Tablets",
          status: "normal",
          currentInventory: 64,
          runOutDate: "Jan 28",
          unitPrice: 12.0,
          recommendedQuantity: 150,
          orderValue: 1800,
        },
        {
          id: "li-6",
          skuCode: "OMEP20",
          name: "Omeprazole 20mg Capsules",
          status: "low-stock",
          currentInventory: 30,
          runOutDate: "Jan 25",
          unitPrice: 7.5,
          recommendedQuantity: 200,
          orderValue: 1500,
        },
      ],
    },
    {
      id: "clearpath-rx",
      vendorName: "ClearPath Rx",
      value: 6480,
      skuCount: 4,
      earliestStockout: "Jan 24",
      poSummary: {
        poNumber: "PO-1042",
        value: 6480,
        leadTimeDays: 5,
        leadTimeEta: "Jan 27",
        confidencePercent: 85,
        confidenceLabel: "Medium",
        skuCount: 4,
        skuNote: "1 at risk",
      },
      demandSignal: {
        summary:
          "Seasonal uptick in cardiovascular medications. Supplier confirmed allocation for priority items. Monitor cold-chain compliance for biologics.",
      },
      riskFactors: [
        {
          id: "rf-4",
          label: "Delivery delayed by 2 days",
          severity: "warning",
        },
        {
          id: "rf-5",
          label: "Partial fill possible on Insulin SKU",
          severity: "warning",
        },
      ],
      lineItems: [
        {
          id: "li-7",
          skuCode: "INSGLA",
          name: "Insulin Glargine 100u/mL Vial",
          status: "urgent",
          currentInventory: 8,
          runOutDate: "Jan 24",
          unitPrice: 42.0,
          recommendedQuantity: 60,
          orderValue: 2520,
        },
        {
          id: "li-8",
          skuCode: "METOP50",
          name: "Metoprolol Succinate 50mg",
          status: "normal",
          currentInventory: 52,
          runOutDate: "Jan 29",
          unitPrice: 11.0,
          recommendedQuantity: 180,
          orderValue: 1980,
        },
        {
          id: "li-9",
          skuCode: "AMLO5",
          name: "Amlodipine 5mg Tablets",
          status: "low-stock",
          currentInventory: 24,
          runOutDate: "Jan 26",
          unitPrice: 9.0,
          recommendedQuantity: 180,
          orderValue: 1620,
        },
        {
          id: "li-10",
          skuCode: "RAMIP10",
          name: "Ramipril 10mg Capsules",
          status: "normal",
          currentInventory: 40,
          runOutDate: "Jan 31",
          unitPrice: 9.0,
          recommendedQuantity: 40,
          orderValue: 360,
        },
      ],
    },
    {
      id: "summit-pharma",
      vendorName: "Summit Pharma Supplies",
      value: 4960,
      skuCount: 5,
      earliestStockout: "Jan 28",
      poSummary: {
        poNumber: "PO-1047",
        value: 4960,
        leadTimeDays: 4,
        leadTimeEta: "Jan 26",
        confidencePercent: 88,
        confidenceLabel: "High",
        skuCount: 5,
        skuNote: "All clear",
      },
      demandSignal: {
        summary:
          "Steady dispensing demand across all SKUs. No significant RX trend changes expected this week.",
      },
      riskFactors: [
        {
          id: "rf-6",
          label: "Partial fill confirmed (80/160 units)",
          severity: "warning",
        },
      ],
      lineItems: [
        {
          id: "li-11",
          skuCode: "SERT50",
          name: "Sertraline 50mg Tablets",
          status: "low-stock",
          currentInventory: 18,
          runOutDate: "Jan 28",
          unitPrice: 14.0,
          recommendedQuantity: 200,
          orderValue: 2800,
        },
        {
          id: "li-12",
          skuCode: "CITAL20",
          name: "Citalopram 20mg Tablets",
          status: "normal",
          currentInventory: 56,
          runOutDate: "Feb 1",
          unitPrice: 10.5,
          recommendedQuantity: 120,
          orderValue: 1260,
        },
        {
          id: "li-13",
          skuCode: "QUETP25",
          name: "Quetiapine 25mg Tablets",
          status: "normal",
          currentInventory: 42,
          runOutDate: "Jan 30",
          unitPrice: 11.0,
          recommendedQuantity: 80,
          orderValue: 880,
        },
        {
          id: "li-14",
          skuCode: "DIAZ5",
          name: "Diazepam 5mg Tablets",
          status: "normal",
          currentInventory: 35,
          runOutDate: "Jan 29",
          unitPrice: 6.5,
          recommendedQuantity: 100,
          orderValue: 650,
        },
        {
          id: "li-15",
          skuCode: "ZOPICLONE",
          name: "Zopiclone 7.5mg Tablets",
          status: "normal",
          currentInventory: 70,
          runOutDate: "Feb 3",
          unitPrice: 8.0,
          recommendedQuantity: 60,
          orderValue: 480,
        },
      ],
    },
    {
      id: "alliance-medical",
      vendorName: "Alliance Medical Wholesale",
      value: 5040,
      skuCount: 8,
      earliestStockout: "Feb 2",
      poSummary: {
        poNumber: "PO-1051",
        value: 5040,
        leadTimeDays: 2,
        leadTimeEta: "Jan 24",
        confidencePercent: 95,
        confidenceLabel: "High",
        skuCount: 8,
        skuNote: "All clear",
      },
      demandSignal: {
        summary:
          "Chronic disease medication demand steady. Winter cold season driving increased OTC demand for analgesics.",
      },
      riskFactors: [
        {
          id: "rf-7",
          label: "Price increase: Atorvastatin 20mg +20%",
          severity: "info",
        },
      ],
      lineItems: [
        {
          id: "li-16",
          skuCode: "ATOR40",
          name: "Atorvastatin 40mg Tablets",
          status: "normal",
          currentInventory: 80,
          runOutDate: "Feb 2",
          unitPrice: 14.0,
          recommendedQuantity: 120,
          orderValue: 1680,
        },
        {
          id: "li-17",
          skuCode: "SIMVA20",
          name: "Simvastatin 20mg Tablets",
          status: "normal",
          currentInventory: 95,
          runOutDate: "Feb 4",
          unitPrice: 9.0,
          recommendedQuantity: 100,
          orderValue: 900,
        },
        {
          id: "li-18",
          skuCode: "IBU400",
          name: "Ibuprofen 400mg Tablets",
          status: "normal",
          currentInventory: 60,
          runOutDate: "Jan 31",
          unitPrice: 5.0,
          recommendedQuantity: 200,
          orderValue: 1000,
        },
        {
          id: "li-19",
          skuCode: "PARA500",
          name: "Paracetamol 500mg Tablets",
          status: "normal",
          currentInventory: 48,
          runOutDate: "Jan 29",
          unitPrice: 4.0,
          recommendedQuantity: 300,
          orderValue: 1200,
        },
        {
          id: "li-20",
          skuCode: "NAPROX",
          name: "Naproxen 500mg Tablets",
          status: "normal",
          currentInventory: 72,
          runOutDate: "Feb 3",
          unitPrice: 8.5,
          recommendedQuantity: 80,
          orderValue: 680,
        },
        {
          id: "li-21",
          skuCode: "CODEIN30",
          name: "Codeine 30mg Tablets",
          status: "normal",
          currentInventory: 55,
          runOutDate: "Jan 30",
          unitPrice: 12.0,
          recommendedQuantity: 60,
          orderValue: 720,
        },
        {
          id: "li-22",
          skuCode: "TRAMA50",
          name: "Tramadol 50mg Capsules",
          status: "normal",
          currentInventory: 90,
          runOutDate: "Feb 5",
          unitPrice: 11.0,
          recommendedQuantity: 60,
          orderValue: 660,
        },
        {
          id: "li-23",
          skuCode: "CELECOX",
          name: "Celecoxib 200mg Capsules",
          status: "normal",
          currentInventory: 65,
          runOutDate: "Feb 1",
          unitPrice: 16.0,
          recommendedQuantity: 40,
          orderValue: 640,
        },
      ],
    },
    {
      id: "pharmalink-co",
      vendorName: "PharmaLink Co.",
      value: 5480,
      skuCount: 5,
      earliestStockout: "Jan 27",
      poSummary: {
        poNumber: "PO-1002",
        value: 5480,
        leadTimeDays: 2,
        leadTimeEta: "Jan 24",
        confidencePercent: 90,
        confidenceLabel: "High",
        skuCount: 5,
        skuNote: "1 backordered",
      },
      demandSignal: {
        summary:
          "Diabetes medication demand up 12% week-over-week. Insulin and oral hypoglycaemic categories driving growth.",
      },
      riskFactors: [
        {
          id: "rf-8",
          label: "Warfarin 5mg backordered until Feb 2",
          severity: "critical",
        },
        {
          id: "rf-9",
          label: "Cold-chain compliance verified",
          severity: "info",
        },
      ],
      lineItems: [
        {
          id: "li-24",
          skuCode: "MET1000",
          name: "Metformin 1000mg Tablets",
          status: "normal",
          currentInventory: 110,
          runOutDate: "Jan 30",
          unitPrice: 10.0,
          recommendedQuantity: 300,
          orderValue: 3000,
        },
        {
          id: "li-25",
          skuCode: "GLIMEP4",
          name: "Glimepiride 4mg Tablets",
          status: "low-stock",
          currentInventory: 22,
          runOutDate: "Jan 27",
          unitPrice: 13.0,
          recommendedQuantity: 100,
          orderValue: 1300,
        },
        {
          id: "li-26",
          skuCode: "SITAGLIP",
          name: "Sitagliptin 100mg Tablets",
          status: "normal",
          currentInventory: 58,
          runOutDate: "Feb 1",
          unitPrice: 22.0,
          recommendedQuantity: 60,
          orderValue: 1320,
        },
        {
          id: "li-27",
          skuCode: "EMPAGLIFL",
          name: "Empagliflozin 10mg Tablets",
          status: "normal",
          currentInventory: 40,
          runOutDate: "Jan 29",
          unitPrice: 28.0,
          recommendedQuantity: 40,
          orderValue: 1120,
        },
        {
          id: "li-28",
          skuCode: "WARF5",
          name: "Warfarin 5mg Tablets",
          status: "out-of-stock",
          currentInventory: 0,
          runOutDate: "Jan 28",
          unitPrice: 8.0,
          recommendedQuantity: 120,
          orderValue: 960,
        },
      ],
    },
    {
      id: "cardinal-rx",
      vendorName: "Cardinal Rx Direct",
      value: 4200,
      skuCount: 4,
      earliestStockout: "Feb 5",
      poSummary: {
        poNumber: "PO-5444",
        value: 4200,
        leadTimeDays: 3,
        leadTimeEta: "Jan 25",
        confidencePercent: 97,
        confidenceLabel: "Very High",
        skuCount: 4,
        skuNote: "All clear",
      },
      demandSignal: {
        summary:
          "Stable demand for respiratory category. Supplier has excess capacity this week — opportunity for bulk contract pricing on inhalers.",
      },
      riskFactors: [
        {
          id: "rf-10",
          label: "Arriving 2 days early",
          severity: "info",
        },
      ],
      lineItems: [
        {
          id: "li-29",
          skuCode: "SALB100",
          name: "Salbutamol Inhaler 100mcg",
          status: "normal",
          currentInventory: 85,
          runOutDate: "Feb 5",
          unitPrice: 18.0,
          recommendedQuantity: 60,
          orderValue: 1080,
        },
        {
          id: "li-30",
          skuCode: "BECLO200",
          name: "Beclomethasone 200mcg Inhaler",
          status: "normal",
          currentInventory: 72,
          runOutDate: "Feb 3",
          unitPrice: 24.0,
          recommendedQuantity: 40,
          orderValue: 960,
        },
        {
          id: "li-31",
          skuCode: "TIOTROPIUM",
          name: "Tiotropium 18mcg Inhaler",
          status: "normal",
          currentInventory: 50,
          runOutDate: "Feb 1",
          unitPrice: 42.0,
          recommendedQuantity: 30,
          orderValue: 1260,
        },
        {
          id: "li-32",
          skuCode: "MONT10",
          name: "Montelukast 10mg Tablets",
          status: "normal",
          currentInventory: 65,
          runOutDate: "Feb 4",
          unitPrice: 15.0,
          recommendedQuantity: 60,
          orderValue: 900,
        },
      ],
    },
  ],
} as const;

export const DEMO_PROCUREMENT_RUN: ProcurementRunData = {
  ...RAW_DATA,
  vendors: RAW_DATA.vendors.map((vendor): VendorOrder => ({
    ...vendor,
    urgency: ProcurementService.deriveVendorUrgency(vendor.lineItems),
  })),
};
