const symptomsKeywords: string[] = [
  'headache',
  'fatigue',
  'fever',
  'cough',
  'sore throat',
  'shortness of breath',
  'muscle aches',
  'nausea',
  'vomiting',
  'diarrhea',
  'abdominal pain',
  'chest pain',
  'joint pain',
  'dizziness',
  'lightheadedness',
  'skin rash',
  'itching',
  'swelling',
  'bruising',
  'numbness',
  'tingling',
  'vision changes',
  'hearing loss',
  'loss of appetite',
  'weight loss',
  'difficulty sleeping',
  'excessive thirst',
  'frequent urination',
  'painful urination',
  'constipation',
  'diabetes symptoms',
  'thyroid symptoms',
  'menstrual irregularities',
  'erectile dysfunction',
  'memory loss',
  'confusion',
  'anxiety',
  'depression',
  'mood swings',
  'panic attacks',
  'insomnia',
  'social withdrawal',
  'suicidal thoughts',
  'hallucinations',
  'seizures',
  'numbness in extremities',
  'speech difficulties',
  'memory problems',
  'balance issues',
  'coordination problems',
  'blurred vision',
  'fatigue after meals',
  'unexplained weight gain',
  'unexplained weight loss',
  'cough',
  'sore throat',
  'fever',
  'headache',
  'fatigue',
  'joint pain',
  'abdominal pain',
  'dizziness',
  'numbness',
  'itching',
  'swelling',
  'bruising',
  'vision changes',
  'hearing loss',
  'skin rash',
  'difficulty sleeping',
  'anxiety',
  'depression',
  'memory loss',
  'balance issues',
  'coordination problems',
  'blurred vision',
  'fatigue after meals',
  'unexplained weight gain',
  'unexplained weight loss',
  'cough',
  'sore throat',
  'fever',
  'headache',
  'fatigue',
  'joint pain',
  'abdominal pain',
  'dizziness',
  'numbness',
  'itching',
  'swelling',
  'bruising',
  'vision changes',
  'hearing loss',
  'skin rash',
  'difficulty sleeping',
  'anxiety',
  'depression',
  'memory loss',
  'balance issues',
  'coordination problems',
  'fatigue after meals',
  'unexplained weight gain',
  'unexplained weight loss',
  'chest pain',
  'joint swelling',
  'abdominal swelling',
  'muscle weakness',
  'shortness of breath',
  'coughing up blood',
  'blood in stool',
  'blood in urine',
  'headaches with visual disturbances',
  'lightheadedness upon standing',
  'high blood pressure',
  'low blood pressure',
  'irregular heartbeat',
  'difficulty concentrating',
  'difficulty speaking',
  'difficulty swallowing',
  'hoarseness',
  'night sweats',
  'chills',
  'skin discoloration',
  'hair loss',
  'joint stiffness',
  'mood changes',
  'sensitivity to light',
  'sensitivity to noise',
  'abdominal cramping',
  'dental problems',
  'bleeding gums',
  'joint redness',
  'joint warmth',
  'muscle cramps',
  'muscle stiffness',
  'tingling in extremities',
  'unexplained fever',
  'unexplained weight fluctuations',
  'unexplained fatigue',
  'unexplained pain',
]

export default symptomsKeywords