"use client"

import { useChat } from "ai/react"
import { FC, FormEvent, useState, ChangeEvent } from "react"
import { MdOutlineSubdirectoryArrowLeft } from "react-icons/md"
import { useKindeBrowserClient } from "@kinde-oss/kinde-auth-nextjs"
import { LoginLink } from "@kinde-oss/kinde-auth-nextjs/components"
import ChatWindow from "@/components/chatbot/ChatWindow"
import LogoNav from "@/components/LogoNav"
import Input from "@/components/Input"
import Button from "@/components/Button"
import symptomsKeywords from "@/utils/symptomsKeywords"
import Caption from "@/components/Caption"
import logo from "../../../public/pharmchat.svg"
import Spinner from "@/components/Spinner"
 


const Page: FC = () => {
  const { messages, input, handleInputChange, handleSubmit } = useChat();
  const [isButtonDisabled, setIsButtonDisabled] = useState(true);
  const [error, setError] = useState("");
  const { isAuthenticated, isLoading } = useKindeBrowserClient();

  const isHealthRelated = (text: string) =>
    symptomsKeywords.some(keyword => text.toLowerCase().includes(keyword));

  const handleHealthSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (isHealthRelated(input)) {
      setError("");
      handleSubmit(e);
    } else {
      setError("Please ask a health-related question.");
    }
  };

  const handleInputChangeAndCheck = (
    e: ChangeEvent<HTMLInputElement> | ChangeEvent<HTMLTextAreaElement>
  ) => {
    const value = e.currentTarget.value;
    handleInputChange(e);
    setIsButtonDisabled(!isHealthRelated(value));
    if (error) setError("");
  };


  if (isLoading) {
    return <Spinner />;
  }

  if (!isAuthenticated) {
    return (
      <div>
        You have to <LoginLink>Login</LoginLink> to see this page
      </div>
    );
  }

  return (
    <div className="bg-black h-[100dvh] w-full flex flex-col justify-between items-center">
      <LogoNav logo={logo} />
      <ChatWindow
        messages={messages}
        modalTitle="Welcome to Pharmchat Chatbot!"
        modalDescription="This is an AI model (GPT-2) that only responds to health-related questions. Please specify symptoms or the sickness itself (e.g., How can I reduce fever at home?)."
        modalResponse="Note: Due to recent changes in Hugging Face's hosting and plan requirements, this AI model may not work or respond as expected unless you have a paid Inference Endpoint or the model is available for free API inference. This limitation is outside of our control. Answers, if generated, are from a general-purpose AI model and are not medical advice."
      />
      <form
        className="absolute bottom-[3rem] flex flex-row text-white justify-between gap-0 w-[80vw] md:w-[50rem]"
        onSubmit={handleHealthSubmit}
      >
        <Input
          type="text"
          input="chat"
          placeholder="Your health-related question.."
          value={input}
          onChange={handleInputChangeAndCheck}
        />
        <div className="absolute z-30 top-3 right-3">
          <Button
            type="submit"
            height={8}
            width="2rem"
            background="white"
            disabled={isButtonDisabled}
            ariaLabel="Submit Message"
          >
            <MdOutlineSubdirectoryArrowLeft className="text-lg" />
          </Button>
        </div>
      </form>
      {error && (
        <div className="text-red-400 mt-2 mb-2 font-semibold">{error}</div>
      )}
      <Caption
        link="https://huggingface.co/gpt2"
        linkText="GPT-2 Model Info"
        text="This chat won't be saved. Answers are generated by a general-purpose AI model and are not medical advice. "
      />
    </div>
  );
};

export default Page